micronaut:
  application:
    name: sample-micronaut-application
  server:
    port: 8100
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    enabled: true

endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: false

test.property: hello

test:
  url:
    client1.url: http://localhost:8080
    client2.url: http://localhost:8090
    client3.url: http://localhost:8100

credentials:
  users:
    smith: smith123
    scott: scott123
    piomin: piomin123
    test: test123